# Generated by Django 2.0 on 2019-05-13 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('facture', models.FileField(upload_to='home/factures/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=14, null=True)),
                ('mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=5, verbose_name='Code Postale')),
                ('paiement', models.DateTimeField(blank=True, null=True, verbose_name='Dernier Paiement')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fiche',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='facturation',
            name='fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Fiche'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Fiche'),
        ),
    ]
