# Generated by Django 2.0 on 2019-04-29 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=14, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('adresse', models.TextField()),
                ('cp', models.CharField(max_length=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fiche',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fiche'),
        ),
    ]
