# Generated by Django 2.0 on 2019-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190429_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['fiche']},
        ),
        migrations.AlterField(
            model_name='fiche',
            name='cp',
            field=models.CharField(max_length=5, verbose_name='Code Postale'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='mail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
