# Generated by Django 2.0 on 2019-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190430_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
