# Generated by Django 2.0 on 2019-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190430_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=30)),
                ('deliveroo', models.BooleanField()),
                ('ubereat', models.BooleanField(verbose_name='Uber Eat')),
                ('justeat', models.BooleanField(verbose_name='Just Eat')),
            ],
            options={
                'ordering': ['ville'],
            },
        ),
    ]
