# Generated by Django 2.0 on 2019-05-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_villes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villes',
            name='deliveroo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='villes',
            name='justeat',
            field=models.BooleanField(default=False, verbose_name='Just Eat'),
        ),
        migrations.AlterField(
            model_name='villes',
            name='ubereat',
            field=models.BooleanField(default=False, verbose_name='Uber Eat'),
        ),
    ]
