# Generated by Django 2.0 on 2019-05-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190501_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villes',
            name='ville',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
