# Generated by Django 2.0 on 2019-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_villes_cp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villes',
            options={'ordering': (['ville'], ['cp'])},
        ),
    ]
