# Generated by Django 2.0 on 2019-05-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190505_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villes',
            options={'ordering': ['ville']},
        ),
    ]
