# Generated by Django 2.0 on 2019-05-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190505_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villes',
        ),
    ]
