# Generated by Django 2.0 on 2019-05-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_villes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villes',
        ),
    ]
