# Generated by Django 2.0 on 2019-05-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_villes_monoprix'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='auchan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villes',
            name='carrefour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villes',
            name='houra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villes',
            name='intermarche',
            field=models.BooleanField(default=False),
        ),
    ]
