# Generated by Django 2.0 on 2019-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190506_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='ovs',
            field=models.BooleanField(default=False),
        ),
    ]
