# Generated by Django 2.0 on 2019-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_villes_ovs'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='allovoisin',
            field=models.BooleanField(default=False),
        ),
    ]
