# Generated by Django 2.0 on 2019-05-08 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190507_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('facture', models.FileField(upload_to='factures/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fiche')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='villes',
            options={'ordering': ['ville'], 'verbose_name': 'Ville'},
        ),
    ]
