# Generated by Django 2.0 on 2019-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190508_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='shiva',
            field=models.BooleanField(default=False),
        ),
    ]
