# Generated by Django 2.0 on 2019-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_villes_maisonetservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='helpling',
            field=models.BooleanField(default=False),
        ),
    ]
