# Generated by Django 2.0 on 2019-05-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_villes_helpling'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='youpijob',
            field=models.BooleanField(default=False),
        ),
    ]
