# Generated by Django 2.0 on 2019-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_villes_youpijob'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='jemepropose',
            field=models.BooleanField(default=False),
        ),
    ]
