# Generated by Django 2.0 on 2019-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_villes_o2'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='vitalliance',
            field=models.BooleanField(default=False),
        ),
    ]
