# Generated by Django 2.0 on 2019-05-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_villes_vitalliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
