# Generated by Django 2.0 on 2019-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190509_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='etatcivil',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], default='Homme', max_length=1),
            preserve_default=False,
        ),
    ]
