# Generated by Django 2.0 on 2019-05-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_fiche_etatcivil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='etatcivil',
        ),
        migrations.AddField(
            model_name='fiche',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], default='HOMME', max_length=5),
            preserve_default=False,
        ),
    ]
