# Generated by Django 2.0 on 2019-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20190510_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='paiement',
            field=models.DateTimeField(null=True, verbose_name='Dernier Paiement'),
        ),
    ]
