# Generated by Django 2.0 on 2019-05-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_fiche_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier Paiement'),
        ),
    ]
