# Generated by Django 2.0 on 2019-05-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_auto_20190511_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFiche',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=14, null=True)),
                ('mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('cp', models.CharField(max_length=5, verbose_name='Code Postale')),
                ('paiement', models.DateTimeField(blank=True, null=True, verbose_name='Dernier Paiement')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fiche',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
