# Generated by Django 2.0 on 2019-05-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_historicalfiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfiche',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalFiche',
        ),
    ]
