# Generated by Django 2.0 on 2019-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190512_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='ville',
            field=models.CharField(default='POITIERS', max_length=30),
            preserve_default=False,
        ),
    ]
