# Generated by Django 2.0 on 2019-05-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_fiche_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='fiche',
        ),
        migrations.RemoveField(
            model_name='facturation',
            name='fiche',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Facturation',
        ),
        migrations.DeleteModel(
            name='Fiche',
        ),
    ]
