# Generated by Django 2.0 on 2019-05-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
