# Generated by Django 2.0 on 2019-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interne', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='test',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
