# Generated by Django 2.0 on 2019-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interne', '0004_list_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='test',
        ),
    ]
