# Generated by Django 2.0 on 2019-05-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interne', '0006_auto_20190513_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='titre',
        ),
    ]
